<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net10.0\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net10.0\Inventory.Infrastructure.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net10.0\Inventory.Infrastructure.GlobalUsings.g.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net10.0\Inventory.Infrastructure.deps.json" />
    <Content Include="bin\Debug\net10.0\Inventory.Infrastructure.runtimeconfig.json" />
    <Content Include="obj\Debug\net10.0\Inventory.Infrastructure.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Inventory.Infrastructure.csproj.nuget.dgspec.json" />
    <Content Include="obj\project.assets.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net10.0\Inventory.Application.dll" />
    <None Include="bin\Debug\net10.0\Inventory.Application.pdb" />
    <None Include="bin\Debug\net10.0\Inventory.Core.dll" />
    <None Include="bin\Debug\net10.0\Inventory.Core.pdb" />
    <None Include="bin\Debug\net10.0\Inventory.Infrastructure.dll" />
    <None Include="bin\Debug\net10.0\Inventory.Infrastructure.pdb" />
    <None Include="obj\Debug\net10.0\Inventor.89798F14.Up2Date" />
    <None Include="obj\Debug\net10.0\Inventory.Infrastructure.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\Inventory.Infrastructure.assets.cache" />
    <None Include="obj\Debug\net10.0\Inventory.Infrastructure.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\Inventory.Infrastructure.csproj.BuildWithSkipAnalyzers" />
    <None Include="obj\Debug\net10.0\Inventory.Infrastructure.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net10.0\Inventory.Infrastructure.dll" />
    <None Include="obj\Debug\net10.0\Inventory.Infrastructure.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net10.0\Inventory.Infrastructure.genruntimeconfig.cache" />
    <None Include="obj\Debug\net10.0\Inventory.Infrastructure.pdb" />
    <None Include="obj\Debug\net10.0\refint\Inventory.Infrastructure.dll" />
    <None Include="obj\Debug\net10.0\ref\Inventory.Infrastructure.dll" />
    <None Include="obj\Inventory.Infrastructure.csproj.nuget.g.props" />
    <None Include="obj\Inventory.Infrastructure.csproj.nuget.g.targets" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Inventory.Application\Inventory.Application.csproj" />
  </ItemGroup>

</Project>
